name: CICD

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build club-parent Project
        run: mvn clean install -DskipTests
